In [1]:
import numpy as np
import pandas as pd

In [16]:
df = pd.read_csv("/content/adult_with_headers (1).csv")

In [17]:
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [19]:
df.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

handling missing values

In [20]:
from sklearn.impute import SimpleImputer

df.replace(" ?", np.nan, inplace=True)
df.replace("?", np.nan, inplace=True)

num_cols = df.select_dtypes(include=np.number).columns
cat_cols = df.select_dtypes(exclude=np.number).columns

num_imputer = SimpleImputer(strategy="median")
cat_imputer = SimpleImputer(strategy="most_frequent")

df[num_cols] = num_imputer.fit_transform(df[num_cols])
df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])

feature scaling

standard scaling

In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[num_cols] = scaler.fit_transform(df[num_cols])

min max sacling

In [23]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[num_cols] = scaler.fit_transform(df[num_cols])

encoding techniques

one hot encoding

In [24]:
one_hot = pd.get_dummies(df[['sex','income']], drop_first=True)

label encoding

In [25]:
from sklearn.preprocessing import LabelEncoder

label = LabelEncoder()

large_cat = [
    'workclass',
    'education',
    'marital_status',
    'occupation',
    'relationship',
    'race',
    'native_country'
]

for col in large_cat:
    df[col] = label.fit_transform(df[col])

total capital

feature 1

In [26]:
df['capital_total'] = df['capital_gain'] - df['capital_loss']

feature 2

hours worked per age

In [27]:
df['hours_age_ratio'] = df['hours_per_week'] / (df['age'] + 1)

skewed features

In [28]:
df['log_fnlwgt'] = np.log1p(df['fnlwgt'])

loading data set

In [30]:
import numpy as np
import pandas as pd

# load dataset
df= pd.read_csv("/content/adult_with_headers (1).csv")

#first 5rows
print(df.head())

#dataset information
print(df.info())

#summary statistics
print(df.describe())

#checking missing values
print(df.isna().sum())

#Check for '?' values (adult dataset usually stores missing values as '?')
print((df == '?').sum())

   age          workclass  fnlwgt   education  education_num  \
0   39          State-gov   77516   Bachelors             13
1   50   Self-emp-not-inc   83311   Bachelors             13
2   38            Private  215646     HS-grad              9
3   53            Private  234721        11th              7
4   28            Private  338409   Bachelors             13

        marital_status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male
1   Married-civ-spouse     Exec-managerial         Husband   White     Male
2             Divorced   Handlers-cleaners   Not-in-family   White     Male
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female

   capital_gain  capital_loss  hours_per_week  native_country  income
0          2174             0              40   United-States   <=50K
1             0             0              13   United-States   <=50K
2             0             0              40   United-States   <=50K
3             0             0              40   United-States   <=50K
4             0             0              40            Cuba   <=50K
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB
None
                age        fnlwgt  education_num  capital_gain  capital_loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000

       hours_per_week
count    32561.000000
mean        40.437456
std         12.347429
min          1.000000
25%         40.000000
50%         40.000000
75%         45.000000
max         99.000000
age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64
age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

handling missing values

In [31]:
import numpy as np
import pandas as pd
# Replace '?' wiyh NaN
df.replace('?', np.nan, inplace=True)

# Check missing values
print(df.isnull().sum())

# Fill categorical columns with mode
for col in df.select_dtypes(include='object'):
    df[col].fillna(df[col].mode()[0], inplace=True)

# Fill numerical columns with median
for col in df.select_dtypes(include=['int64','float64']):
    df[col].fillna(df[col].median(), inplace=True)

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

/tmp/ipykernel_640/4080306118.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
/tmp/ipykernel_640/4080306118.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

standard scaling

In [32]:
from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler()

num_cols = [
    'age',
    'fnlwgt',
    'education_num',
    'capital_gain',
    'capital_loss',
    'hours_per_week'
]

standard_scaled = standard_scaler.fit_transform(df[num_cols])

min max scaling

In [33]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[num_cols] = scaler.fit_transform(df[num_cols])

one hot encoding

In [34]:
small_cat = [col for col in df.select_dtypes(include='object')
             if df[col].nunique() < 5]

onehot = pd.get_dummies(df, columns=small_cat)

print(onehot.head())

        age          workclass    fnlwgt   education  education_num  \
0  0.301370          State-gov  0.044302   Bachelors       0.800000
1  0.452055   Self-emp-not-inc  0.048238   Bachelors       0.800000
2  0.287671            Private  0.138113     HS-grad       0.533333
3  0.493151            Private  0.151068        11th       0.400000
4  0.150685            Private  0.221488   Bachelors       0.800000

        marital_status          occupation    relationship    race  \
0        Never-married        Adm-clerical   Not-in-family   White
1   Married-civ-spouse     Exec-managerial         Husband   White
2             Divorced   Handlers-cleaners   Not-in-family   White
3   Married-civ-spouse   Handlers-cleaners         Husband   Black
4   Married-civ-spouse      Prof-specialty            Wife   Black

   capital_gain  capital_loss  hours_per_week  native_country  sex_ Female  \
0       0.02174           0.0        0.397959   United-States        False
1       0.00000           0.0        0.122449   United-States        False
2       0.00000           0.0        0.397959   United-States        False
3       0.00000           0.0        0.397959   United-States        False
4       0.00000           0.0        0.397959            Cuba         True

   sex_ Male  income_ <=50K  income_ >50K
0       True           True         False
1       True           True         False
2       True           True         False
3       True           True         False
4      False           True         False

ladel encoding

In [36]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

df_label = df.copy()

for col in df_label.select_dtypes(include='object'):
    df_label[col] = label_encoder.fit_transform(df_label[col])

print(df_label.head())

        age  workclass    fnlwgt  education  education_num  marital_status  \
0  0.301370          7  0.044302          9       0.800000               4
1  0.452055          6  0.048238          9       0.800000               2
2  0.287671          4  0.138113         11       0.533333               0
3  0.493151          4  0.151068          1       0.400000               2
4  0.150685          4  0.221488          9       0.800000               2

   occupation  relationship  race  sex  capital_gain  capital_loss  \
0           1             1     4    1       0.02174           0.0
1           4             0     4    1       0.00000           0.0
2           6             1     4    1       0.00000           0.0
3           6             0     2    1       0.00000           0.0
4          10             5     2    0       0.00000           0.0

   hours_per_week  native_country  income
0        0.397959              39       0
1        0.122449              39       0
2        0.397959              39       0
3        0.397959              39       0
4        0.397959               5       0

feature engineering

In [37]:
df['capital_difference'] = df['capital_gain'] - df['capital_loss']

In [38]:
df['education_age_ ratio']=df['education_num']/df['age']

In [39]:
df['weekly_income_effort'] = df['hours_per_week'] * df['education_num']

In [40]:
import numpy as np

df['capital_gain_log'] = np.log1p(df['capital_gain'])